/**
 * Generates src/icon/icons.generated.ts from @iconify/json.
 *
 * Why not the usual routes:
 *   - The design calls icons by runtime name (`solar:fire-bold-duotone`), so Tailwind's
 *     @iconify/tailwind selectors can't be statically generated for them.
 *   - The design files use the <iconify-icon> web component, which fetches from a CDN. That is
 *     a non-starter for the browser extension's content scripts.
 * So we inline the SVG bodies for an explicit allowlist at build time: offline, no network,
 * and unused icons are still in one module (see the note on tree-shaking below).
 *
 * To add an icon: put its name in ICONS, run `yarn icons`, use it as <StIcon name="…" />.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

/** Every icon the shell, the Progress screen, the Login screen and the profile menu use. Keep sorted by set, then name. */
const ICONS = [
    'logos:google-icon',
    'solar:add-circle-bold',
    'solar:alt-arrow-left-linear',
    'solar:alt-arrow-right-linear',
    'solar:arrow-down-bold',
    'solar:arrow-right-bold',
    'solar:arrow-right-linear',
    'solar:arrow-up-bold',
    'solar:bookmark-bold-duotone',
    'solar:card-2-bold-duotone',
    'solar:chart-2-bold-duotone',
    'solar:check-circle-bold-duotone',
    'solar:clock-circle-bold',
    'solar:crown-bold',
    'solar:crown-bold-duotone',
    'solar:crown-linear',
    'solar:danger-triangle-bold',
    'solar:documents-bold-duotone',
    'solar:download-minimalistic-bold',
    'solar:fire-bold',
    'solar:fire-bold-duotone',
    'solar:hamburger-menu-linear',
    'solar:history-2-bold-duotone',
    'solar:layers-minimalistic-bold-duotone',
    'solar:lock-keyhole-minimalistic-bold-duotone',
    'solar:logout-2-linear',
    'solar:microphone-3-bold-duotone',
    'solar:monitor-bold-duotone',
    'solar:moon-bold-duotone',
    'solar:moon-sleep-bold-duotone',
    'solar:notebook-bold',
    'solar:notebook-bold-duotone',
    'solar:play-bold',
    'solar:rocket-2-bold-duotone',
    'solar:settings-bold-duotone',
    'solar:settings-linear',
    'solar:sun-2-bold-duotone',
    'solar:user-linear',
];

const setCache = new Map();
function loadSet(prefix) {
    if (!setCache.has(prefix)) {
        const path = resolve(root, 'node_modules/@iconify/json/json', `${prefix}.json`);
        setCache.set(prefix, JSON.parse(readFileSync(path, 'utf8')));
    }
    return setCache.get(prefix);
}

/** Follows one level of alias indirection, which is all the Solar set uses. */
function resolveIcon(set, name) {
    if (set.icons?.[name]) return { ...set.icons[name] };
    const alias = set.aliases?.[name];
    if (!alias) return null;
    const base = resolveIcon(set, alias.parent);
    return base ? { ...base, ...alias } : null;
}

const entries = [];
const missing = [];

for (const full of ICONS) {
    const [prefix, name] = full.split(':');
    const set = loadSet(prefix);
    const icon = resolveIcon(set, name);
    if (!icon) {
        missing.push(full);
        continue;
    }
    entries.push({
        name: full,
        body: icon.body,
        width: icon.width ?? set.width ?? 24,
        height: icon.height ?? set.height ?? 24,
    });
}

if (missing.length) {
    console.error(`build-icons: not found in @iconify/json:\n  ${missing.join('\n  ')}`);
    process.exit(1);
}

const out = `/* eslint-disable */
// GENERATED by scripts/build-icons.mjs — do not edit. Add names to that script's ICONS list.
export interface IconDef {
    body: string;
    width: number;
    height: number;
}

export const icons: Record<string, IconDef> = {
${entries
    .map((e) => `    ${JSON.stringify(e.name)}: { body: ${JSON.stringify(e.body)}, width: ${e.width}, height: ${e.height} },`)
    .join('\n')}
};

export type IconName = keyof typeof icons;
`;

mkdirSync(resolve(root, 'src/icon'), { recursive: true });
writeFileSync(resolve(root, 'src/icon/icons.generated.ts'), out);
console.log(`build-icons: wrote ${entries.length} icons`);
