name: Deploy on EC2
on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  GIGET_AUTH_TOKEN: ${{ secrets.GIGET_AUTH_TOKEN }}
  NUXT_API_URL: ${{ vars.NUXT_API_URL }}
  IMAGE_TAG_SERVER: dashboard-${{ github.sha }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Create env file
      # This file goes to docker and used in building the image
      - name: Create .env file
        run: |
          echo "NUXT_API_URL=${NUXT_API_URL}" > .env

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIGET_AUTH_TOKEN }}

      # build docker image
      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_SERVER }} --build-arg GIGET_AUTH_TOKEN=${GIGET_AUTH_TOKEN} .

      # push docker image
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_SERVER }}
