name: Deploy on EC2 From ECR Registry
on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: me-south-1 # Bahrain region
  AWS_CONTAINER_REGISTRY: subturtle
  IMAGE_TAG: dashboard-latest
  GIGET_AUTH_TOKEN: ${{ secrets.GIGET_AUTH_TOKEN }}
  NUXT_API_URL: ${{ vars.NUXT_API_URL }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Create env file
      # This file goes to docker and used in building the image
      - name: Create .env file
        run: |
          echo "NUXT_API_URL=${NUXT_API_URL}" > .env
          echo "GIGET_AUTH_TOKEN=${GIGET_AUTH_TOKEN}" >> .env

      # Prepare environment for arm build
      # Set up QEMU and Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.AWS_CONTAINER_REGISTRY }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build --platform linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose pull dashboard
            docker compose up -d --force-recreate dashboard
